---
#-------------------------------
# General Site Settings

title: Studio K
logo:
author: themefisher
description: this is meta description
email: kyj8028@hotmail.com
phone: +82 10
address: Seoul, Korea
copyright: Copyright &copy; 2015 All Rights Reserved # by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  # - { name: Blog, link: "/blog" }
  # - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Youngjae <br> Entrepreneur

social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/youngjaekang/" }
  - { icon: "ti-youtube", link: "https://www.youtube.com/channel/UC7rSOHMlQ9UDbFuET76CO5Q" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: 기술로 인간의 삶을 이롭게 하는 비즈니스를 운영합니다. 다양한 분야의 전문가들과 협업하여 세상에 긍정적인 영향을 만들어갑니다.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Quickly identify problems, research them in depth, and develop an optimized strategy plan for problem resolution."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Based on the brainstorming and design thinking of experts, we proceed with service design and development."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Once the project is complete, deploy it in the appropriate form. It can be done in many forms, including IT services, media, and magazines."

# My Team Section
team:
  - title: "Changhyuk Choi"
    image: "assets/images/team/member-1.png"
    designation: "Product Owner"

  - title: "Sanghee Lim"
    image: "assets/images/team/member-2.png"
    designation: "Designer"

  - title: "Jian Lee"
    image: "assets/images/team/member-3.png"
    designation: "Brand Marketer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: 경영/전략, color: "#fdb157", value: "100%" }
  - { name: 재무관리, color: "#9473e6", value: "80%" }
  - { name: IT/기술, color: "#bdecf6", value: "90%" }
  - { name: 기획/PM, color: "#ffbcaa", value: "90%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Strategic Planning,
      icon: "icon-1.png",
      date: "Dec 2015 - Nov 2020",
      organization: "K-Auction",
    }
  - {
      name: CEO,
      icon: "icon-2.png",
      date: "Aug 2017 - Dec 2018",
      organization: "E.Lighthouse",
    }
  - {
      name: Business Planning,
      icon: "icon-3.png",
      date: "Dec 2020 - Present",
      organization: "Pulmuone Holdings",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Data Analysis & Programming,
      date: "2018",
      organization: "Korea Data Agency",
    }
  - {
      name: Architecture & Design,
      date: "2012",
      organization: "College of Architecture, Myongji University",
    }
  # - {
  #     name: Architecture & Design,
  #     date: "2012",
  #     organization: "College of Architecture, Myongji University",
  #   }
  # - {
  #     name: Secondary School Certificate,
  #     date: "1998",
  #     organization: "Cardiff School",
  #   }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Business Consulting,
      icon: ti-bar-chart,
      description: "Provides solutions to all levels of problems from initial business construction to mature operations, including strategy, sales, marketing, ERP, and financial management.",
      active: ,# Add true to select section
    }
  - {
      name: IT Product Development,
      icon: ti-cloud,
      description: "We provide overall services such as planning, programming, design, and project management to build IT products. In particular, we provide customized services through data-driven decisions.",
      active: true, # Add true to select section
    }
  - {
      name: Media Production,
      icon: ti-video-camera,
      description: "We specialize in content planning and video production. It provides total service based on the ability to integrate various media technologies and contents.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Youngjae Kang"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO"
    content: "We're committed to solving intelligence, to advance science and benefit humanity. Make your life easier with our product. <strong>We work on most complex and interesting challenges in the world.</strong> What if solving one problem could unlock solutions to thousands more?"

  # - name: "Jesica Gomez"
  #   image: "assets/images/testimonial/client-1.png"
  #   designation: "CEO, Funder"
  #   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  # - name: "Jesica Gomez"
  #   image: "assets/images/testimonial/client-1.png"
  #   designation: "CEO, Funder"
  #   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: kyj8028@hotmail.com
